
package com.mycompany.quanlybaidoxe.giaodienAdmin;

import static com.mycompany.quanlybaidoxe.LogIn.spotType.*;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author trung
 */
public class khoitaoform extends javax.swing.JDialog {

    /**
     * Creates new form khoitaoform
     */
    public static void deleteFile(String filePath) {
        File file = new File(filePath);
        
        if (file.exists()) {
            if (file.delete()) {
                System.out.println("File đã được xóa thành công: " + filePath);
            } else {
                System.out.println("Không thể xóa file: " + filePath);
            }
        } else {
            System.out.println("File không tồn tại: " + filePath);
        }
    }
    public khoitaoform(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        soLuongthoSo = new javax.swing.JTextField();
        khoitao = new javax.swing.JButton();
        dong = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        khoitaoGiathoSo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        soLuongxeMay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        khoitaoGiaxeMay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        soLuongoTo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        khoitaoGiaoTo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        soLuongcDung = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        khoitaoGiacDung = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khởi tạo số lượng chỗ đỗ xe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nhập số lượng chỗ đỗ xe thô sơ cần khởi tạo:");

        soLuongthoSo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongthoSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongthoSoActionPerformed(evt);
            }
        });

        khoitao.setText("Khởi tạo");
        khoitao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khoitaoActionPerformed(evt);
            }
        });

        dong.setText("Đóng");
        dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongActionPerformed(evt);
            }
        });

        jLabel2.setText("Lưu ý: Khi khởi tạo lại toàn bộ dữ liệu trong bãi đỗ xe cũ sẽ được xóa toàn bộ và khởi tạo mới lại từ đầu. Hãy cân nhắc ");

        jLabel4.setText("trước khi khởi tạo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Khởi tạo giá chỗ đỗ xe thô sơ:");

        khoitaoGiathoSo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nhập số lượng chỗ đỗ xe máy cần khởi tạo:");

        soLuongxeMay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongxeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongxeMayActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Khởi tạo giá chỗ đỗ xe máy:");

        khoitaoGiaxeMay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Nhập số lượng chỗ đỗ xe ô tô cần khởi tạo:");

        soLuongoTo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongoTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongoToActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Khởi tạo giá chỗ đỗ xe ô tô:");

        khoitaoGiaoTo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Nhập số lượng chỗ đỗ xe chuyên dụng cần khởi tạo:");

        soLuongcDung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongcDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongcDungActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Khởi tạo giá chỗ đỗ xe chuyên dụng:");

        khoitaoGiacDung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(khoitao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dong)
                .addGap(110, 110, 110))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(soLuongxeMay, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(soLuongthoSo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(khoitaoGiathoSo)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(khoitaoGiaxeMay)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(soLuongoTo, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(khoitaoGiaoTo)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(soLuongcDung, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(khoitaoGiacDung))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soLuongthoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khoitaoGiathoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soLuongxeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khoitaoGiaxeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soLuongoTo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khoitaoGiaoTo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soLuongcDung, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khoitaoGiacDung, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(khoitao)
                    .addComponent(dong))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soLuongthoSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongthoSoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongthoSoActionPerformed

    private void khoitaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khoitaoActionPerformed
        String thoSo = soLuongthoSo.getText();
        String xeMay = soLuongxeMay.getText();
        String oTo = soLuongoTo.getText();
        String cDung = soLuongcDung.getText();
        
        if(isNumeric(thoSo)&&isNumeric(xeMay)&&isNumeric(oTo)&&isNumeric(cDung)){
            deleteFile("data_parkSpot.xml");
            parkingSpot.resetNextID();
            try{
                long TS = Long.parseLong(thoSo);
                long XM = Long.parseLong(xeMay);
                long OT = Long.parseLong(oTo);
                long CD = Long.parseLong(cDung);
                // Khởi tạo xe thô sơ
                for (long i=1;i<=TS;i++){
                    parkingSpot pkS = new parkingSpot();
                    long gia = Long.parseLong(khoitaoGiathoSo.getText());
                    pkS.setGia(gia);
                    try {
                        convertSpotXML.addParkingSpotToXML(pkS,xeThoso,"data_parkSpot.xml");
                    } catch (ParserConfigurationException ex) {
                        Logger.getLogger(khoitaoform.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (TransformerException ex) {
                        Logger.getLogger(khoitaoform.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                // Khởi tạo xe máy
                for (long i=1;i<=XM;i++){
                    parkingSpot pkS = new parkingSpot();
                    long gia = Long.parseLong(khoitaoGiaxeMay.getText());
                    pkS.setGia(gia);
                    try {
                        convertSpotXML.addParkingSpotToXML(pkS,xeGanmay,"data_parkSpot.xml");
                    } catch (ParserConfigurationException ex) {
                        Logger.getLogger(khoitaoform.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (TransformerException ex) {
                        Logger.getLogger(khoitaoform.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                //Khởi tạo xe ô tô
                for (long i=1;i<=OT;i++){
                    parkingSpot pkS = new parkingSpot();
                    long gia = Long.parseLong(khoitaoGiaoTo.getText());
                    pkS.setGia(gia);
                    try {
                        convertSpotXML.addParkingSpotToXML(pkS,xeOto,"data_parkSpot.xml");
                    } catch (ParserConfigurationException ex) {
                        Logger.getLogger(khoitaoform.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (TransformerException ex) {
                        Logger.getLogger(khoitaoform.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                // khởi tạo xe chuyên dụng
                for (long i=1;i<=CD;i++){
                    parkingSpot pkS = new parkingSpot();
                    long gia = Long.parseLong(khoitaoGiacDung.getText());
                    pkS.setGia(gia);
                    try {
                        convertSpotXML.addParkingSpotToXML(pkS,xeChuyendung,"data_parkSpot.xml");
                    } catch (ParserConfigurationException ex) {
                        Logger.getLogger(khoitaoform.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (TransformerException ex) {
                        Logger.getLogger(khoitaoform.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                admin mainFrame = (admin) getParent();
                mainFrame.loadDulieulenBang1();
                khoitaothanhcong moi = new khoitaothanhcong(khoitaoform.this);
                moi.setVisible(true);
                
            }catch(NumberFormatException e){
                
            }
        }else{
            khoitaokhongthanhcong dialogmoi = new khoitaokhongthanhcong(khoitaoform.this);
            dialogmoi.setVisible(true);
        }
    }//GEN-LAST:event_khoitaoActionPerformed

    private void dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongActionPerformed
            dispose();
    }//GEN-LAST:event_dongActionPerformed

    private void soLuongxeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongxeMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongxeMayActionPerformed

    private void soLuongoToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongoToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongoToActionPerformed

    private void soLuongcDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongcDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongcDungActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton khoitao;
    private javax.swing.JTextField khoitaoGiacDung;
    private javax.swing.JTextField khoitaoGiaoTo;
    private javax.swing.JTextField khoitaoGiathoSo;
    private javax.swing.JTextField khoitaoGiaxeMay;
    private javax.swing.JTextField soLuongcDung;
    private javax.swing.JTextField soLuongoTo;
    private javax.swing.JTextField soLuongthoSo;
    private javax.swing.JTextField soLuongxeMay;
    // End of variables declaration//GEN-END:variables
    // Hàm kiểm tra có phải là số hay không
    private boolean isNumeric(String input) {
       try {
            Double.parseDouble(input); 
            return true;
        } catch (NumberFormatException e) {
            return false; 
        }
    }

}
